import {createSupabaseServerClient} from "../../../../lib/supabase-server";
import {NextResponse} from "next/server";
async function duffel(path:string,init?:RequestInit){const token=process.env.DUFFEL_ACCESS_TOKEN;if(!token)throw new Error("Duffel is not configured.");const r=await fetch("https://api.duffel.com"+path,{...init,headers:{"Authorization":"Bearer "+token,"Duffel-Version":"v2","Accept":"application/json","Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d?.errors?.[0]?.message||"Duffel request failed.");return d.data;}
export async function POST(request:Request){const supabase=await createSupabaseServerClient();if(!supabase)return NextResponse.json({error:"Authentication service is not configured."},{status:503});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"You must be signed in to complete a booking."},{status:401});const paystack=process.env.PAYSTACK_SECRET_KEY;try{const {payment_reference,offer_id,passengers}=await request.json();if(!paystack||!payment_reference||!offer_id||!Array.isArray(passengers)||!passengers.length)return NextResponse.json({error:"Payment reference, offer and passengers are required."},{status:400});
const vr=await fetch("https://api.paystack.co/transaction/verify/"+encodeURIComponent(payment_reference),{headers:{Authorization:"Bearer "+paystack,Accept:"application/json"},cache:"no-store"});const vd=await vr.json();if(!vr.ok||vd.data?.status!=="success")return NextResponse.json({error:"Payment has not been verified."},{status:402});
if(vd.data?.metadata?.offer_id&&vd.data.metadata.offer_id!==offer_id)return NextResponse.json({error:"Payment is not linked to this flight offer."},{status:409});
const idempotencyKey="travora-"+payment_reference;
const offer=await duffel("/air/offers/"+encodeURIComponent(offer_id));if(offer.id!==offer_id)return NextResponse.json({error:"Offer validation failed."},{status:409});
const expected=Math.round(Number(offer.total_amount)*100);if(Number(vd.data.amount)!==expected||vd.data.currency!==offer.total_currency)return NextResponse.json({error:"Paid amount does not match the current flight fare. No airline booking was created."},{status:409});
const order=await duffel("/air/orders",{method:"POST",headers:{"X-Idempotency-Key":idempotencyKey},body:JSON.stringify({data:{type:"instant",selected_offers:[offer_id],passengers,payments:[{type:"balance",amount:offer.total_amount,currency:offer.total_currency}]}})});
const bookingReference=order.booking_reference;const {error}=await supabase.from("bookings").insert({user_id:user.id,booking_reference:bookingReference,provider:"duffel",provider_order_id:order.id,status:"confirmed",currency:offer.total_currency,total_amount:offer.total_amount,booked_at:new Date().toISOString()});if(error&&error.code!=="23505")throw new Error("Airline order created, but Travora could not save the reservation.");return NextResponse.json({ok:true,order,provider_order_id:order.id,booking_reference:bookingReference,status:"confirmed",payment_reference});}catch(e:any){return NextResponse.json({error:e?.message||"Booking could not be completed."},{status:502});}}