"use client";
import { useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase";

export default function AuthPage() {
 const [mode,setMode]=useState<"signin"|"signup">("signin"); const [message,setMessage]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [fullName,setFullName]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");const supabase=createSupabaseBrowserClient();if(!supabase){setMessage("Supabase is not configured. Add the Travora Supabase environment variables in Vercel.");return;}setBusy(true);const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:window.location.origin+"/dashboard"}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){setMessage(result.error.message);return;}if(mode==="signup"&&!result.data.session){setMessage("Account created. Check your email to confirm your address before signing in.");return;}window.location.href="/dashboard";}
 async function google(){const supabase=createSupabaseBrowserClient();if(!supabase){setMessage("Supabase is not configured.");return;}const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/dashboard"}});if(error)setMessage(error.message);}
 return <main className="authPage"><div className="authCard"><a className="brand authBrand" href="/">Trav<span>ora</span></a><h1>{mode==="signin"?"Welcome back":"Create your Travora account"}</h1><p className="muted">{mode==="signin"?"Sign in to manage your flights and reservations.":"Save passengers, bookings and upcoming flights in one place."}</p><form onSubmit={submit}>{mode==="signup"&&<div className="field authField"><label>Full name</label><input required value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name"/></div>}<div className="field authField"><label>Email</label><input required value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com"/></div><div className="field authField"><label>Password</label><input required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="At least 8 characters"/></div><button className="authSubmit" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form><button className="googleBtn" onClick={google}>Continue with Google</button>{mode==="signin"&&<a className="forgot" href="/auth/reset">Forgot password?</a>}{message&&<div className="authNotice">{message}</div>}<p className="switch">{mode==="signin"?"Don't have an account?":"Already have an account?"} <button onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMessage("")}}>{mode==="signin"?"Create one":"Sign in"}</button></p><a className="backHome" href="/">← Back to Travora</a></div></main>;
}