"use client";
import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase";
type Passenger={id:string;first_name:string;last_name:string;nationality:string|null;passport_number:string|null};
export default function Checkout(){
 const [user,setUser]=useState<any>(null),[passengers,setPassengers]=useState<Passenger[]>([]),[selected,setSelected]=useState(""),[offer,setOffer]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState("");
 useEffect(()=>{(async()=>{const s=createSupabaseBrowserClient();if(!s){setMessage("Supabase is not configured.");setLoading(false);return;}const {data}=await s.auth.getUser();if(!data.user){window.location.href="/auth";return;}setUser(data.user);const id=new URLSearchParams(window.location.search).get("offer");if(!id){setMessage("No flight offer was selected.");setLoading(false);return;}const r=await fetch("/api/flights/revalidate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({offer_id:id})});const d=await r.json();if(!r.ok){setMessage(d.error||"This offer is no longer available.");setLoading(false);return;}setOffer(d.offer);const q=await s.from("passengers").select("id,first_name,last_name,nationality,passport_number").order("created_at",{ascending:false});setPassengers(q.data||[]);setLoading(false);})();},[]);
 async function book(){if(!selected){setMessage("Select a passenger first.");return;}if(!email||!phone){setMessage("Add your contact email and phone number.");return;}const passenger=passengers.find(p=>p.id===selected);if(!passenger||!offer){return;}setBusy(true);try{const r=await fetch("/api/flights/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({offer_id:offer.id,passengers:[{id:passenger.id,first_name:passenger.first_name,last_name:passenger.last_name,email,phone,nationality:passenger.nationality,passport_number:passenger.passport_number}],payment:{amount:offer.total_amount,currency:offer.total_currency}})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Booking could not be created.");const ref=d.booking_reference||("TRV-"+Math.random().toString(36).slice(2,8).toUpperCase());const s=createSupabaseBrowserClient();const ins=await s?.from("bookings").insert({user_id:user.id,booking_reference:ref,status:d.status||"confirmed",provider:"duffel",currency:offer.total_currency,total_amount:offer.total_amount});if(ins?.error)throw new Error("Airline order created, but Travora could not save the reservation.");window.location.href="/dashboard?booking="+encodeURIComponent(ref);}catch(e:any){setMessage(e.message||"Unable to complete booking.");}finally{setBusy(false);}}
 if(loading)return <main className="authPage"><div className="authCard"><p>Preparing your flight…</p></div></main>;
 return <main><header><div className="container nav"><a className="brand" href="/">Trav<span>ora</span></a><a className="btn btnGhost" href="/dashboard">Back to dashboard</a></div></header><section className="section"><div className="container checkout"><p className="eyebrow">FLIGHT CHECKOUT</p><h1>Review your journey</h1>{message&&<div className="authNotice">{message}</div>}{offer&&<><div className="card checkoutSummary"><div><span className="muted">Airline</span><strong>{offer.owner?.name||"Airline"}</strong></div><div><span className="muted">Route</span><strong>{offer.slices?.map((s:any)=>s.origin?.iata_code+" → "+s.destination?.iata_code).join(" · ")}</strong></div><div><span className="muted">Fare</span><strong>{offer.total_currency} {offer.total_amount}</strong></div></div><div className="card"><h2>Passenger</h2><p className="muted">Choose a saved passenger for this reservation.</p><select className="checkoutSelect" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select passenger</option>{passengers.map(p=><option value={p.id} key={p.id}>{p.first_name} {p.last_name}</option>)}</select><div className="modalGrid"><div className="field"><label>Contact email</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder={user?.email||"you@example.com"}/></div><div className="field"><label>Phone number</label><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+234…"/></div></div><div className="modalActions"><button className="btn btnPrimary" disabled={busy||!selected} onClick={book}>{busy?"Preparing…":"Continue to payment"}</button></div></div></>}</div></section></main>;
}