"use client";
import { useEffect,useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase";

type User={email?:string;name?:string};
export default function Dashboard(){
 const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState("");
 useEffect(()=>{const s=createSupabaseBrowserClient();if(!s){setMessage("Supabase is not configured.");setLoading(false);return;} s.auth.getUser().then(({data,error})=>{if(error||!data.user){window.location.href="/auth";return;}setUser({email:data.user.email,name:data.user.user_metadata?.full_name||data.user.email?.split("@")[0]});setLoading(false);});},[]);
 async function signOut(){const s=createSupabaseBrowserClient();if(s) await s.auth.signOut();window.location.href="/";}
 if(loading)return <main className="authPage"><div className="authCard"><p>Loading your Travora account…</p></div></main>;
 return <main><header><div className="container nav"><a className="brand" href="/">Trav<span>ora</span></a><div className="dashboardNav"><span className="welcome">Hi, {user?.name}</span><button className="btn btnPrimary" onClick={signOut}>Sign out</button></div></div></header><section className="section"><div className="container"><p className="eyebrow">MY TRAVORA</p><h1 className="dashboardTitle">Your flight hub</h1><p className="muted">Manage your journeys, passengers and reservations from one place.</p>{message&&<div className="authNotice">{message}</div>}<div className="dashboardGrid"><article className="card"><span className="cardIcon">✈</span><h3>Upcoming flights</h3><p className="muted">Your confirmed and upcoming journeys will appear here.</p><a className="cardAction" href="/#flights">Search flights</a></article><article className="card"><span className="cardIcon">👤</span><h3>Saved passengers</h3><p className="muted">Keep passenger details ready for faster bookings.</p><button className="cardAction">Manage passengers</button></article><article className="card"><span className="cardIcon">🎫</span><h3>Manage booking</h3><p className="muted">Retrieve a reservation using your Travora booking reference.</p><button className="cardAction">Find booking</button></article></div><div className="accountBar"><div><strong>Signed in as</strong><span>{user?.email}</span></div><a href="/auth/reset">Change password</a></div></div></section></main>
}