"use client";
import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "../../lib/supabase";

type Passenger={id:string;first_name:string;last_name:string;nationality:string|null;passport_number:string|null};
type Booking={id:string;booking_reference:string;status:string;provider:string|null;currency:string;total_amount:number|null;booked_at?:string|null;provider_order_id?:string|null};

export default function Dashboard(){
 const [user,setUser]=useState<any>(null),[passengers,setPassengers]=useState<Passenger[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [showPassenger,setShowPassenger]=useState(false),[showBooking,setShowBooking]=useState(false),[first,setFirst]=useState(""),[last,setLast]=useState(""),[nationality,setNationality]=useState(""),[passport,setPassport]=useState(""),[reference,setReference]=useState("");

 useEffect(()=>{(async()=>{const s=createSupabaseBrowserClient();if(!s){setMessage("Supabase is not configured.");setLoading(false);return;}const {data,error}=await s.auth.getUser();if(error||!data.user){window.location.href="/auth";return;}setUser(data.user);const [p,b]=await Promise.all([s.from("passengers").select("id,first_name,last_name,nationality,passport_number").order("created_at",{ascending:false}),s.from("bookings").select("id,booking_reference,status,provider,currency,total_amount,booked_at,provider_order_id").order("booked_at",{ascending:false})]);if(p.error||b.error)setMessage(p.error?.message||b.error?.message||"Unable to load account data.");setPassengers(p.data||[]);setBookings(b.data||[]);setLoading(false);})();},[]);

 async function addPassenger(e:React.FormEvent){e.preventDefault();const s=createSupabaseBrowserClient();if(!s||!user)return;setBusy(true);const {data,error}=await s.from("passengers").insert({user_id:user.id,first_name:first,last_name:last,nationality:nationality||null,passport_number:passport||null}).select("id,first_name,last_name,nationality,passport_number").single();setBusy(false);if(error){setMessage(error.message);return;}setPassengers(prev=>[data,...prev]);setFirst("");setLast("");setNationality("");setPassport("");setShowPassenger(false);setMessage("Passenger saved.");}
 async function findBooking(e:React.FormEvent){e.preventDefault();const s=createSupabaseBrowserClient();if(!s||!user)return;setBusy(true);const {data,error}=await s.from("bookings").select("id,booking_reference,status,provider,currency,total_amount").eq("booking_reference",reference.trim().toUpperCase()).maybeSingle();setBusy(false);if(error){setMessage(error.message);return;}if(!data){setMessage("No booking was found for that reference.");return;}setBookings(prev=>[data,...prev.filter(b=>b.id!==data.id)]);setReference("");setShowBooking(false);setMessage("Booking loaded.");}
 async function refreshBookings(){const s=createSupabaseBrowserClient();if(!s||!user)return;const {data}=await s.from("bookings").select("id,booking_reference,status,provider,currency,total_amount,booked_at,provider_order_id").eq("user_id",user.id).order("booked_at",{ascending:false});setBookings(data||[]);} async function signOut(){const s=createSupabaseBrowserClient();if(s)await s.auth.signOut();window.location.href="/";}

 if(loading)return <main className="authPage"><div className="authCard"><p>Loading your Travora account…</p></div></main>;
 return <main><header><div className="container nav"><a className="brand" href="/">Trav<span>ora</span></a><div className="dashboardNav"><span className="welcome">Hi, {user?.user_metadata?.full_name||user?.email?.split("@")[0]}</span><button className="btn btnPrimary" onClick={signOut}>Sign out</button></div></div></header>
 <section className="section"><div className="container"><p className="eyebrow">MY TRAVORA</p><h1 className="dashboardTitle">Your flight hub</h1><p className="muted">Manage your journeys, passengers and reservations from one place.</p><button className="cardAction" onClick={refreshBookings}>↻ Refresh trips</button>{message&&<div className="authNotice">{message}</div>}
 <div className="dashboardGrid">
 <article className="card"><span className="cardIcon">✈</span><h3>Upcoming flights</h3><p className="muted">{bookings.length?bookings.length+" reservation"+(bookings.length===1?"":"s")+" saved.":"No reservations yet."}</p><a className="cardAction" href="/#flights">Search flights</a></article>
 <article className="card"><span className="cardIcon">👤</span><h3>Saved passengers</h3><p className="muted">{passengers.length?passengers.length+" passenger"+(passengers.length===1?"":"s")+" saved.":"Save passenger details for faster bookings."}</p><button className="cardAction" onClick={()=>setShowPassenger(true)}>Manage passengers</button></article>
 <article className="card"><span className="cardIcon">🎫</span><h3>Manage booking</h3><p className="muted">Retrieve a reservation using its Travora booking reference.</p><button className="cardAction" onClick={()=>setShowBooking(true)}>Find booking</button></article></div>
 {bookings.length>0&&<section className="dataSection"><div className="sectionHeading"><h2>My trips</h2><a className="cardAction" href="/#flights">+ New flight</a></div><div className="tripList">{bookings.map(b=><article className="tripCard" key={b.id}><div className="tripTop"><div><span className="muted">BOOKING</span><strong>{b.booking_reference}</strong></div><span className="statusPill">{b.status}</span></div><div className="tripRoute"><span>✈</span><div><strong>{b.provider||"Flight provider"}</strong><span>{b.booked_at?new Date(b.booked_at).toLocaleDateString():"Date pending"}</span></div></div><div className="tripBottom"><strong>{b.total_amount==null?"Amount pending":b.currency+" "+Number(b.total_amount).toLocaleString()}</strong><a className="btn btnGhost" href={"/booking?booking="+encodeURIComponent(b.booking_reference)}>View trip</a></div></article>)}</div></section>}
 {passengers.length>0&&<section className="dataSection"><h2>Saved passengers</h2><div className="dataList">{passengers.map(p=><div className="dataRow" key={p.id}><div><strong>{p.first_name} {p.last_name}</strong><span>{p.nationality||"Nationality not set"}{p.passport_number?" · Passport saved":""}</span></div></div>)}</div></section>}
 <div className="accountBar"><div><strong>Signed in as</strong><span>{user?.email}</span></div><a href="/auth/reset">Change password</a></div></div></section>
 {showPassenger&&<div className="modalBackdrop"><form className="modal" onSubmit={addPassenger}><h2>Add passenger</h2><div className="modalGrid"><div className="field"><label>First name</label><input required value={first} onChange={e=>setFirst(e.target.value)}/></div><div className="field"><label>Last name</label><input required value={last} onChange={e=>setLast(e.target.value)}/></div><div className="field"><label>Nationality</label><input value={nationality} onChange={e=>setNationality(e.target.value)} placeholder="Nigerian"/></div><div className="field"><label>Passport number</label><input value={passport} onChange={e=>setPassport(e.target.value)}/></div></div><div className="modalActions"><button type="button" className="btn btnGhost" onClick={()=>setShowPassenger(false)}>Cancel</button><button className="btn btnPrimary" disabled={busy}>{busy?"Saving…":"Save passenger"}</button></div></form></div>}
 {showBooking&&<div className="modalBackdrop"><form className="modal" onSubmit={findBooking}><h2>Find a booking</h2><p className="muted">Enter a booking reference belonging to your Travora account.</p><div className="field"><label>Booking reference</label><input required value={reference} onChange={e=>setReference(e.target.value)} placeholder="TRV12345"/></div><div className="modalActions"><button type="button" className="btn btnGhost" onClick={()=>setShowBooking(false)}>Cancel</button><button className="btn btnPrimary" disabled={busy}>{busy?"Searching…":"Find booking"}</button></div></form></div>}
 </main>;
}